BASEDIR=$(TOPDIR)/elkscmd

include $(BASEDIR)/Makefile-rules

LOCALFLAGS = -DNO_LP

PRGS = ekermit
OBJS = main.o kermit.o elksio.o

all: $(PRGS)

$(PRGS): $(OBJS)
	$(LD) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	$(RM) *.o $(PRGS)
